---
- name: reto 1 ansible
  hosts: student1-win1
  become: yes
  gather_facts: no
  
  tasks:

  - name: Get hostname
    ansible.windows.win_command:
      cmd: echo $HOSTNAME
    register: hostname
    
  - ansible.builtin.debug:
      msg: The hostname is {{ hostname }}
