---
- name: reto 1 ansible
  hosts: student1-win1
  become: yes
  gather_facts: no

- name: Get hostname
    ansible.windows.win_command:
      cmd: echo $HOSTNAME 
      register: hostname
    
  - ansible.builtin.debug:
      msg: The hostname is {{ hostname }}

- name: Get version Windows
    ansible.windows.win_command:
      cmd: echo $VERSION 
      register: version
    
  - ansible.builtin.debug:
      msg: The version is {{ version }}
      
  - name: Check install Firewall and W3Svc
    ansible.windows.win_feature:
       name: "{{ item }}"
       state: present
    loop:
    - Firewall
    - W3Svc
     
  - name: Check started Firewall and W3Svc
    ansible.windows.win_service:
      name: "{{ item }}"
      state: started
    loop:
    - Firewall
    - W3Svc
    
  - name: Enable W3Svc in Firewall
    win_firewall_rule:
       name: W3Svc
       localport: 80
       action: allow
       direction: in
       protocol: tcp
       state: present
       enabled: yes  
       
  - name: Create directory /tmp/reto1
    ansible.windows.win_file:
      path: C:\tmp\reto1
      state: directory
      
  - name: Create a file reto1_content
    ansible.windows.win_file:
      path: C:\tmp\reto1\reto1_content.txt
      state: touch
            
  - name: Create a file reto1_content
    ansible.windows.win_file:
      path: C:\tmp\reto1\reto1_content.txt
      state: touch      
      
  - name: Change the hostname to sample-hostname
    ansible.windows.win_hostname:
      name: riki
    register: res
    
  - name: Reboot
    ansible.windows.win_reboot:
    when: res.reboot_required
    
  - name: Update all installed packages
    chocolatey.chocolatey.win_chocolatey:
      name: all
      state: latest      
      
  - name: Set the contents of a file
    ansible.windows.win_copy:
      content: $VERSION
      dest: C:\tmp\reto1\reto1_content.txt
      
  - name: Backup file
    ansible.windows.win_copy:
      src: C:\tmp\reto1\reto1_content.txt
      dest: C:\tmp\reto1\reto1_content.backup
      
  - name: Add a line to a file 
    community.windows.win_lineinfile:
      path: C:\tmp\reto1\reto1_content.backup
      line: ESTA ES UNA PRUEBA
