---
- name: remove the iis web service
  hosts: windows

  tasks:
  - name: uninstall iis    
    win_service:
      name: W3Svc
      state: stopped

  - name: delete iis service
    win_feature:
      name: Web-Server
      state: absent

  - name: Delete website index.html
    win_file:
      dest: C:\Inetpub\wwwroot\index.html
      state: absent

  - name: Reinicio del servicio
    ansible.windows.win_reboot:        