---
- name: ejercicio 1 ansible
  hosts: test
  gather_facts: true 
  vars: 
    message: "HOLA MUNDO" 

  tasks:

##LITERAL 1

  - name: creacio usuario student
    ansible.builtin.user:
      name: student
      state: present
      password: master20

##LITERAL 2

  - name: creacion directorio myplaybook
    ansible.builtin.file:
      path: /etc/myplaybook
      state: directory
	owner: student
	group: student
	mode: 0644

##LITERAL 3

   - name: Copy using inline content
     ansible.builtin.copy:
   	content: '# This file was moved to /etc/other.conf'
	dest: /etc/mine.conf 
   
##LITERAL 4

   - name: imprimir distribucion RedHat   	
   -ansible.builtin.debug:
	 msg: La distribucion de ansible es {{ ansible_distribution.stdout_lines }}
     when: ansible_distribution == "RedHat"

##LITERAL 5

   - name: verificacion de paquetes firewalld
     ansible.builtin.yum:
	 name: firewalld
       state: latest

   - name: verificacion de paquetes httpd
     ansible.builtin.yum:
	 name: httpd
       state: latest	

##LITERAL 6

   - name: servicio activo y habilitado de paquetes firewalld 
     ansible.builtin.service:
	 name: firewalld
       enabled: true
       state: started

   - name: servicio activo y habilitado de paquetes httpd
     ansible.builtin.service:
	 name: httpd
       enabled: true
       state: started

##LITERAL 7

   - name: permitir servicio httpd en el firewall
     ansible.posix.firewalld:
	 service: httpd
	 port: tcp
       permanent: true
       state: enable

##LITERAL 8 DUDA

    - name: listar e imprimir actualizaciones disponibles
      ansible.builtin.shell:
	  rpm -qa --last | grep "$(date +%a\ %d\ %b\ %Y)" |cut -f 1 -d " "
      register: result
       args:
	 warn: no
    
    -ansible.builtin.debug:
	msg="{{ result.stdout_lines }}"

##LITERAL 9

    - name: salida de comandos uptime
      ansible.builtin.command: uptime > /tmp/evidencias; cat /etc/resolv.connf -->> /tmp/envidencias; df -h >> /tmp/evidencias 
	 args:
	 creates: /tmp/evidencias

 ##LITERAL 10

	- name: Actualizar todos los paquetes del servidor excluyendo el paquete httpd
 	  ansible.builtin.yum:
   	    name: "*"
    	    state: latest
          exclude: httpd*

##LITERAL 11

	- name: Reinicio del servidor
        ansible.builtin.reboot:
	    reboot_timeout. 3600

##LITERAL 12

	  - name: Copy using inline content
     	    ansible.builtin.copy:
   		content: {{ ansible_distribution }}
		dest: /tmp/distribution  
