---
- name: reto 2 ansible
  hosts: web
  become: yes
  gather_facts: yes
  
  pre_tasks:
    - name: install packages Postgresql
      ansible.builtin.dnf:
        name= {{ item }}
        state= present
      with_items:
        - postgresql
        - postgresql-server

    - name: install Python packages
      ansible.builtin.pip:
        name= {{ item }}
        state= present
      with_items:
        - psycopg2-binary
        
  tasks:
    - name: verificar si el PostgreSQL esta inicializado
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: initialize PostgreSQL
      ansible.builtin.shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists
      
      
    - name: start and enable services PostgreSQL
      ansible.builtin.service:
        name={{ item }}
        state= started
        enabled= yes
      with_items:
        - postgresql
